/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface GranRange {
    /**
    * Valor maximo do range
    */
    'max': number;
    /**
    * Valor minimo do range
    */
    'min': number;
    /**
    * Valor atual do range
    */
    'value': number;
  }
}

declare global {


  interface HTMLGranRangeElement extends Components.GranRange, HTMLStencilElement {}
  var HTMLGranRangeElement: {
    prototype: HTMLGranRangeElement;
    new (): HTMLGranRangeElement;
  };
  interface HTMLElementTagNameMap {
    'gran-range': HTMLGranRangeElement;
  }
}

declare namespace LocalJSX {
  interface GranRange {
    /**
    * Valor maximo do range
    */
    'max'?: number;
    /**
    * Valor minimo do range
    */
    'min'?: number;
    /**
    * Disparado quando o usuario movimenta o range
    */
    'onPress'?: (event: CustomEvent<any>) => void;
    /**
    * Disparado quando o usuario solta o range
    */
    'onPressed'?: (event: CustomEvent<any>) => void;
    /**
    * Valor atual do range
    */
    'value'?: number;
  }

  interface IntrinsicElements {
    'gran-range': GranRange;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'gran-range': LocalJSX.GranRange & JSXBase.HTMLAttributes<HTMLGranRangeElement>;
    }
  }
}


